---
#- name: Ensure notepad++ is installed and using chocolatey
#  win_chocolatey:
#    name: notepadplusplus
#    state: latest
 
- name: Create localadmin user and place in Administrators group
  win_user:
    name: localadmin
    password: "P@ssw0rd1!"
    groups: ["Administrators"]
